INSERT INTO PRODUCT ( NAME, AMOUNT) VALUES ('테스트상품1', '10000');
INSERT INTO PRODUCT ( NAME, AMOUNT) VALUES ('테스트상품2', '20000');
INSERT INTO MEMBER (EMAIL, PASSWORD) VALUES ('dsound72@gmail.com', '$2a$10$.fD6G0doRgnGOgaSFoTekuH69z9R0POyrWHQBABAG0a4XOv5Cq1b2');
INSERT INTO USER_ROLES SELECT ID, 2 FROM MEMBER WHERE EMAIL = 'dsound72@gmail.com';